### ISSUE TITLE
Create and organize GitHub wiki

### ISSUE THREAD

**Issue by skilgoreT** [simbulus-io/Topi#4]
We will use a wiki hosted by GitHub to organize and communicate project data.  Should include

Team - names and contacs
Schedule - important deadlines/milestones
Knowlege Base - e.g AWS account information, functional specifications,  programming tips and tricks .. just about anything that your teammates might find useful

You will need to learn markdown - I find it easier to actually checkout the wiki and edit the source in VSCode rather than using the GitHub interface. [Instructions Here ]( https://docs.github.com/en/communities/documenting-your-project-with-wikis/adding-or-editing-wiki-pages#adding-or-editing-wiki-pages-locally)

Its okay to link out from the Wiki to Drive hosted Google Docs if Markdown doesn't meet the needs of the info you are capturing

**Comment by skilgoreT** [comment]
[Here is a link to the Wiki ](https://github.com/simbulus-io/Topi/wiki)

**Comment by laurabroderick5** [comment]
https://www.markdownguide.org/basic-syntax/
